services:
  db:
    image: postgres:15
    restart: "always"
    env_file:
      - .env
    volumes:
      - db-data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER}"]
      interval: 10s
      retries: 5

  migrate:
    image: migrate/migrate:v4.18.1
    depends_on:
      db:
        condition: service_healthy
    volumes:
      - ./db/migrations:/migrations
    env_file:
      - .env
    restart: "no"
    command: ["-path", "/migrations", "-database", "${DATABASE_URL}", "up"]

  app:
    build: .
    restart: "always"
    env_file:
      - .env
    environment:
      APP_PORTS: "${APP_PORTS}"
      DEBUG: "${DEBUG}"
    ports:
      - "${APP_PORTS}"
    depends_on:
      - db
      - migrate

volumes:
  db-data: