services:
  db:
    image: postgres:15
    restart: "always"
    env_file:
      - .env
    volumes:
      - db-data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER}"]
      interval: 10s
      retries: 5

  migrate:
    image: migrate/migrate:v4.18.1
    depends_on:
      db:
        condition: service_healthy
    volumes:
      - ./db/migrations:/migrations
      - ./status:/status
    env_file:
      - .env
    restart: "no"
    command: ["sh", "-c", "-path", "migrate -path /migrations -database ${DATABASE_URL} up && touch /status/migrate.success || rm -f /status/migrate.success"]

  app:
    build: .
    restart: "always"
    env_file:
      - .env
    environment:
      APP_PORTS: "${APP_PORTS}"
      DEBUG: "${DEBUG}"
    ports:
      - "${APP_PORTS}"
    volumes:
    - ./status:/status
    depends_on:
      - db
      - migrate
    entrypoint: ["sh", "-c", "while [ ! -f /status/migrate.success ]; do sleep 1; done; ./music_info"]

volumes:
  db-data:
